name: CI (RetailDemandX Smoke)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install system deps (LightGBM build tools)
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run unit imports
        run: pytest -q tests/test_imports.py

      - name: Run mini E2E smoke
        run: python ci/ci_smoke.py

      - name: Upload artifacts (reports & registry manifest)
        uses: actions/upload-artifact@v4
        with:
          name: rdx-artifacts
          path: |
            artifacts/reports/**
            artifacts/registry/staging/current/manifest.json